language: cpp
before_install:
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update
install:
    - sudo apt-get install ninja-build
    - wget https://github.com/zengcan/gn-bin/raw/master/linux64/gn
    - chmod u+x gn
script:
    - ./gn gen -v out
    - ninja -v -C out
